name: surbi_web
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1      # ← 추가
  riverpod_annotation: ^2.3.5   # ← 추가 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0    # ← 추가
  build_runner: ^2.4.8          # ← 추가

flutter:
  uses-material-design: true